CustomerViews/Controllers/CartController.cs
using CustomerViews.IServices;
using CustomerViews.Models;
using Data.ModelsClass;
using Microsoft.AspNetCore.Mvc;
using _1_API.ViewModel.GioHangChiTiet;
using _1_API.ViewModel.HoaDon;
using _1_API.ViewModel.HoaDonChiTiet;

namespace CustomerViews.Controllers
{
    public class CartController : Controller
    {
        private readonly ILogger<CartController> _logger;
        private readonly IAllServices _services;
        public CartController(ILogger<CartController> logger, IAllServices services)
        {
            _logger = logger;
            _services = services;
        }
        public async Task<IActionResult> Index()
        {
            string idgh = HttpContext.Session.GetString("idgh");

            var lstSPCT = await _services.GetAll<SanphamChitiet>(Connection.api + "SanphamChitiets/Get-All");
            var lstGHCT = await _services.GetAll<GiohangChitiet>(Connection.api + "GioHangChiTiets/Get-All");
            var lstKC = await _services.GetAll<KichCo>(Connection.api + "KichCos/Get-All");
            var lstMauSac = await _services.GetAll<MauSac>(Connection.api + "MauSacs/Get-All");
            ViewData["lstMauSac"] = lstMauSac.ToList();
            ViewData["lstKC"] = lstKC.ToList();
            ViewData["lstSPCT"] = lstSPCT.ToList();
            decimal tongtien = 0;
            var ls = lstGHCT.Where(x => x.IdGioHang.ToString() == idgh);
            foreach (var item in ls)
            {
                tongtien += (item.SoLuong * item.GiaBan);
            }
            ViewBag.tt = tongtien;
            return View(ls);
        }
        public async Task<IActionResult> TangSL(Guid id)
        {

            string idgh = HttpContext.Session.GetString("idgh");

            var lstSizeSP = await _services.GetAll<SizeSanPham>(Connection.api + "SizeSanPhams/Get-All");
            var lstSanphamChitiet = await _services.GetAll<SanphamChitiet>(Connection.api + "SanphamChitiets/Get-All");
            var lstKichCo = await _services.GetAll<KichCo>(Connection.api + "KichCos/Get-All");
            var respons = await _services.GetAll<GiohangChitiet>(Connection.api + "GioHangChiTiets/Get-All");


            var respon = respons.FirstOrDefault(x => x.IdGioHang.ToString() == idgh && x.Id == id);
            var kc = lstKichCo.FirstOrDefault(x => x.Id == respon.IdKichCo);
            var sizesp = lstSizeSP.FirstOrDefault(x => x.IdSize == kc.Id);

            var lstsl = (from a in lstSanphamChitiet.ToList()
                         join b in lstSizeSP.ToList() on a.Id equals b.IdSanPhamChiTiet
                         join c in lstKichCo.ToList().Where(x => x.Id == kc.Id) on b.IdSize equals c.Id
                         join d in respons.ToList() on c.Id equals d.IdKichCo
                         select new { a, b, c, d }).FirstOrDefault();

            respon.SoLuong++;
            if (respon.SoLuong > sizesp.SoLuong)
            {
                return Ok("Vượt quá số lượng trong kho");
            }
            else
            {
                await _services.Update(Connection.api + "GioHangChiTiets/Update/", respon, respon.Id);
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> GiamSL(Guid id)
        {
            string idgh = HttpContext.Session.GetString("idgh");
            var respons = await _services.GetAll<GiohangChitiet>(Connection.api + "GioHangChiTiets/Get-All");
            var lstSizeSP = await _services.GetAll<SizeSanPham>(Connection.api + "SizeSanPhams/Get-All");
            var lstKichCo = await _services.GetAll<KichCo>(Connection.api + "KichCos/Get-All");
            var respon = respons.FirstOrDefault(x => x.IdGioHang.ToString() == idgh && x.Id == id);
            var kc = lstKichCo.FirstOrDefault(x => x.Id == respon.IdKichCo);
            var sizesp = lstSizeSP.FirstOrDefault(x => x.IdSize == kc.Id);

            --respon.SoLuong;
            if (respon.SoLuong <= 0)
            {
                await _services.Remove<GiohangChitiet>(Connection.api + "GioHangChiTiets/GetById/", Connection.api + "GioHangChiTiets/Delete/", respon.Id);
                return RedirectToAction("Index");
            }
            await _services.Update(Connection.api + "GioHangChiTiets/Update/", respon, respon.Id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Add(Guid ma, string idSize, string soluong)
        {
            string idkh = HttpContext.Session.GetString("idkh");
            if (idkh == null)
            {
                return RedirectToAction("DangNhap", "Login");
            }
            else
            {
                if (idSize == null)
                {
                    return Ok("Vui lòng chọn size");
                }
                else if (int.Parse(soluong) <= 0)
                {
                    return Ok("Vui lòng nhập số lượng");
                }
                else
                {
                    var maND = await _services.GetAll<KhachHang>(Connection.api + "KhachHangs/Get-All");
                    var maKH = maND.FirstOrDefault(p => p.Id.ToString() == idkh);

                    var laymaGH = await _services.GetAll<GioHang>(Connection.api + "GioHangs/Get-All");
                    var maGH = laymaGH.FirstOrDefault(p => p.IdKH.ToString() == idkh);

                    var lstSanphamChitiet = await _services.GetAll<SanphamChitiet>(Connection.api + "SanphamChitiets/Get-All");
                    var spct = lstSanphamChitiet.FirstOrDefault(x => x.Id == ma);


                    var lstSizeSP = await _services.GetAll<SizeSanPham>(Connection.api + "SizeSanPhams/Get-All");
                    var sizesp = lstSizeSP.FirstOrDefault(x => x.IdSize == Guid.Parse(idSize) && x.IdSanPhamChiTiet == ma);
                    var lstKichCo = await _services.GetAll<KichCo>(Connection.api + "KichCos/Get-All");
                    var dataa = await _services.GetAll<GiohangChitiet>(Connection.api + "GioHangChiTiets/Get-All");
                    var data = dataa.FirstOrDefault(p => p.IdSPChitiet == spct.Id && p.IdGioHang == maGH.Id && p.IdKichCo.ToString() == idSize);
                    if (data == null)
                    {
                        if (int.Parse(soluong) > sizesp.SoLuong)
                        {
                            return Ok("Vượt quá số lượng trong kho");
                        }
                        else
                        {
                            CreateGioHangChiTiet ghct = new CreateGioHangChiTiet()
                            {
                                IdGioHang = maGH.Id,
                                IdSPChitiet = spct.Id,
                                GiaBan = spct.GiaBan,
                                SoLuong = int.Parse(soluong),
                                IdKichCo = Guid.Parse(idSize),
                            };
                            await _services.Add(Connection.api + "GioHangChiTiets/", ghct);
                            return RedirectToAction("Index");
                        }

                    }
                    else
                    {
                        var respon = (from a in lstSanphamChitiet.ToList()
                                      join b in lstSizeSP.ToList() on a.Id equals b.IdSanPhamChiTiet
                                      join c in lstKichCo.ToList() on b.IdSize equals c.Id
                                      where a.Id == ma
                                      select new { a, b, c });

                        var sl = respon.FirstOrDefault(x => x.a.Id == ma);
                        data.SoLuong++;
                        if (data.SoLuong > sl.b.SoLuong)
                        {
                            return Ok("Vượt quá số lượng trong kho");
                        }
                        else
                        {
                            await _services.Update(Connection.api + "GioHangChiTiets/Update/", data, data.Id);
                        }
                    }
                }
                return RedirectToAction("Index");
            }
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            await _services.Remove<GiohangChitiet>(Connection.api + "GioHangChiTiets/GetById/", Connection.api + "GioHangChiTiets/Delete/", id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> MuaHang()
        {
            string idgh = HttpContext.Session.GetString("idgh");
            var lstSPCT = await _services.GetAll<SanphamChitiet>(Connection.api + "SanphamChitiets/Get-All");
            var lstKC = await _services.GetAll<KichCo>(Connection.api + "KichCos/Get-All");
            ViewData["lstKC"] = lstKC.ToList();
            ViewData["lstSPCT"] = lstSPCT.ToList();
            var lstGHCT = await _services.GetAll<GiohangChitiet>(Connection.api + "GioHangChiTiets/Get-All");
            var ls = lstGHCT.Where(x => x.IdGioHang.ToString() == idgh);
            decimal tongtien = 0;
            foreach (var item in ls)
            {
                tongtien += (item.SoLuong * item.GiaBan);
            }
            ViewBag.tt = tongtien;
            return View(ls);
        }

        public async Task<IActionResult> CheckMaGiamGia(string magiamgia)
        {

            string idgh = HttpContext.Session.GetString("idgh");

            var lstMa = await _services.GetAll<MaGiamGia>(Connection.api + "MaGiamGias/Get-All");
            var lstSPCT = await _services.GetAll<SanphamChitiet>(Connection.api + "SanphamChitiets/Get-All");
            var lstKC = await _services.GetAll<KichCo>(Connection.api + "KichCos/Get-All");
            var lstGHCT = await _services.GetAll<GiohangChitiet>(Connection.api + "GioHangChiTiets/Get-All");

            var ls = lstGHCT.Where(x => x.IdGioHang.ToString() == idgh);
            ViewData["lstKC"] = lstKC.ToList();
            ViewData["lstSPCT"] = lstSPCT.ToList();

CustomerViews/Controllers/SanPhamController.cs
using System.Linq;
using _1_API.ViewModel.SanPham;
using _1_API.ViewModel.SanphamChitiet;
using _1_API.ViewModel.SizeSanPham;
using _1_API.ViewModel.TheLoai;
using CustomerViews.IServices;
using CustomerViews.Models;
using Data.ModelsClass;
using Microsoft.AspNetCore.Mvc;

namespace CustomerViews.Controllers
{
    public class SanPhamController : Controller
{
        private readonly ILogger<SanPhamController> _logger;
        private readonly IWebHostEnvironment _webHost;
        private readonly IAllServices _services;
        public SanPhamController(ILogger<SanPhamController> logger, IWebHostEnvironment webHost, IAllServices services)
        {
            _logger = logger;
            _webHost = webHost;
            _services = services;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var lstSPCT = await _services.GetAll<SanphamChitiet>(Connection.api + "SanphamChitiets/Get-All");
            var lstSP = await _services.GetAll<SanPham>(Connection.api + "SanPhams/Get-All");
            var lstTL = await _services.GetAll<TheLoai>(Connection.api + "TheLoais/Get-All");

            ViewData["lstSP"] = lstSP.ToList();
            ViewData["lstTL"] = lstTL.ToList();
            return View(lstSPCT.ToList());
        }
        [HttpGet]
        public async Task<IActionResult> Index1(string idTL)
        {
            var lstSPCT = await _services.GetAll<SanphamChitiet>(Connection.api + "SanphamChitiets/Get-All");
            var lstSP = await _services.GetAll<SanPham>(Connection.api + "SanPhams/Get-All");
            var lstTL = await _services.GetAll<TheLoai>(Connection.api + "TheLoais/Get-All");
            var lstTLSP = await _services.GetAll<TheLoaiSanPham>(Connection.api + "TheLoaiSanPhams/Get-All");
            var lstIDSP = lstTLSP.Where(x => x.IdTheLoai == Guid.Parse(idTL)).Select(x => x.IdChiTietSP).ToList();

            ViewData["lstSP"] = lstSP.ToList();
            ViewData["lstTL"] = lstTL.ToList();
            ViewData["idTL"] = Guid.Parse(idTL);
            return View("Index",lstSPCT.Where(x=> lstIDSP.Contains(x.Id)).ToList());
        }

        public async Task<IActionResult> SearchSanPham(string ten, Guid idTheLoai)
        {
            var lstSPCT = await _services.GetAll<SanphamChitiet>(Connection.api + "SanphamChitiets/Get-All");
            var lstTLSP = await _services.GetAll<TheLoaiSanPham>(Connection.api + "TheLoaiSanPhams/Get-All");
            var lstTL = await _services.GetAll<TheLoai>(Connection.api + "TheLoais/Get-All");
            if (!string.IsNullOrEmpty(ten))
                lstSPCT = lstSPCT.Where(x => x.TenSPChiTiet.ToLower().Contains(ten.ToLower())).ToList();
            if (idTheLoai != Guid.Empty)
            {
                var lstSPCT_id = lstTLSP.Where(x => x.IdTheLoai == idTheLoai).Select(x => x.IdChiTietSP);
                lstSPCT = lstSPCT.Where(x => lstSPCT_id.Contains(x.Id)).ToList();
            }
            var lstNgayT = (from a in lstSPCT.ToList()
                            orderby a.NgayTao descending
                            select new SanphamChitiet()
                            {
                                Id = a.Id,
                                NgayTao = a.NgayTao,
                                GiaBan = a.GiaBan,
                                MaSPChiTiet = a.MaSPChiTiet,
                                TenSPChiTiet = a.TenSPChiTiet,
                                AnhDaiDien = a.AnhDaiDien
                            }).Take(4);
            var lstNoiBat = (from a in lstSPCT.ToList()
                             select new SanphamChitiet()
                             {
                                 Id = a.Id,
                                 NgayTao = a.NgayTao,
                                 GiaBan = a.GiaBan,
                                 MaSPChiTiet = a.MaSPChiTiet,
                                 TenSPChiTiet = a.TenSPChiTiet,
                                 AnhDaiDien = a.AnhDaiDien
                             }).Take(8);
            ViewData["lstNgayT"] = lstNgayT.ToList();
            ViewData["lstNoiBat"] = lstNoiBat.ToList();
            ViewData["lstTL"] = lstTL.ToList();
            return View("Index", lstSPCT);
        }


    }
}

CustomerViews/Views/Home/Index.cshtml
@using Data.ModelsClass;
@model IEnumerable<Data.ModelsClass.SanphamChitiet>

@{
    ViewData["Title"] = "Home Page";
    var thongbao = ViewData["thongbao"] as string;
    var loginfalse = ViewData["loginfalse"] as string;
    var lstSP = ViewData["lstSP"] as List<SanPham>;
    var lstTL = ViewData["lstTL"] as List<TheLoai>;
    var lstNgayT = ViewData["lstNgayT"] as List<SanphamChitiet>;
    var lstNoiBat = ViewData["lstNoiBat"] as List<SanphamChitiet>;
    string tensp = "";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustomerViews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/home.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CustomerViews.styles.css" asp-append-version="true" />
</head>

<div class="body">
    <div class="container">
        <div class="slide">
            <div id="carouselExampleCaptions"
                 class="carousel slide"
                 data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide-to="0"
                            class="active"
                            aria-current="true"
                            aria-label="Slide 1"></button>
                    <button type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide-to="1"
                            aria-label="Slide 2"></button>
                    <button type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide-to="2"
                            aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active" data-bs-interval="2000">
                        <img src="~/img/slide-1.jpg"
                             class="d-block w-100"
                             alt="..."
                             height="450px" />
                        <div class="carousel-caption d-none d-md-block"
                             style="max-width: 450px">
                            <h5 style="font-size: 40px; font-weight: bold">
                                THE SNEAKER SHOP
                            </h5>
                            <p style="font-size: 14px">
                                Chào mừng bạn đến với ngôi nhà Converse! Tại đây, mỗi một dòng
                                chữ, mỗi chi tiết và hình ảnh đều là những bằng chứng mang dấu
                                ấn lịch sử Converse 100 năm, và đang không ngừng phát triển lớn
                                mạnh.
                            </p>
                        </div>
                    </div>
                    <div class="carousel-item" data-bs-interval="2000">
                        <img src="~/img/slide-2.jpg"
                             class="d-block w-100"
                             alt="..."
                             height="450px" />
                        <div class="carousel-caption d-none d-md-block"
                             style="max-width: 800px; margin-left: 450px">
                            <h5 style="font-size: 40px; font-weight: bold">
                                THE SNEAKER SHOP
                            </h5>
                            <p style="font-size: 14px">
                                Chào mừng bạn đến với ngôi nhà Converse! Tại đây, mỗi một dòng
                                chữ, mỗi chi tiết và hình ảnh đều là những bằng chứng mang dấu
                                ấn lịch sử Converse 100 năm, và đang không ngừng phát triển lớn
                                mạnh.
                            </p>
                        </div>
                    </div>
                    <div class="carousel-item" data-bs-interval="2000">
                        <img src="img/slide-5.jpg"
                             class="d-block w-100"
                             alt="..."
                             height="450px" />
                        <div class="carousel-caption d-none d-md-block"
                             style="max-width: 800px; margin-bottom: 280px">
                            <h5 style="font-size: 40px; font-weight: bold">
                                THE SNEAKER SHOP
                            </h5>
                            <p style="font-size: 14px">
                                Chào mừng bạn đến với ngôi nhà Converse! Tại đây, mỗi một dòng
                                chữ, mỗi chi tiết và hình ảnh đều là những bằng chứng mang dấu
                                ấn lịch sử Converse 100 năm, và đang không ngừng phát triển lớn
                                mạnh.
                            </p>
                        </div>
                    </div>
                </div>
                <button class="carousel-control-prev"
                        type="button"
                        data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next"
                        type="button"
                        data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <!-- Banner body -->
        <div class="banner-body">
            <div class="container">
                <div class="row banner3">
                    <div class="col-4">
                        <div class="thumb">
                            <img src="~/img/banner_1.jpg" alt="" />
                            <img src="~/img/banner_2.jpg" alt="" />
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="thumb">
                            <img src="~/img/banner_3.jpg" alt="" />
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="thumb">
                            <img src="~/img/banner_4.jpg" alt="" />
                            <img src="~/img/banner_5.jpg" alt="" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="title">
            <h2>SẢN PHẨM MỚI</h2>
        </div>
        <br />
        <br />

        @if (Model != null && Model.Any())
        {

            <div class="product">
                <div class="row">
                    @foreach (var product in lstNgayT)
                    {
                        <div class="card-columns col-3" style="border: none">
                            <div class="card h-70 text-center" style="">
                                                <a asp-controller="Home" asp-action="SanPhamChiTiet" asp-route-spct_id="@product.Id">
                                                         <img src="~/img/@product.AnhDaiDien" class="card-img img-fluid" alt="" />
                                                    </a>
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a asp-controller="Home" asp-action="SanPhamChiTiet" asp-route-spct_id="@product.Id">
                                            @Html.DisplayFor(modelItem => product.TenSPChiTiet)
                                           
                                        </a>
                                        <p class="card-text">  <span style="color: #c30005; font-weight: lighter;text-decoration: line-through;"></span>  @Html.DisplayFor(modelItem => product.GiaBan)VND</p>
                                    </h5>
                                    <p class="">
                                        <b>Trạng thái: @(product.TrangThai == 1 ? "Còn hàng" : "Hết hàng")</b>
                                    </p>
                                </div>

                            </div>
                            <br />
                        </div>

                    }
                </div>

            </div>
            <br />
            <div class="more">
                <a asp-controller="SanPham" asp-action="Index">XEM TẤT CẢ</a>
            </div>
        }
        else
        {
            <h3>Không có sản phẩm nào phù hợp</h3>
        }
        <div class="body_banner">
            <div class="row">
                <div class="col-3 imggg"><img src="~/img//m_bn_2_1.jpg" alt="" /></div>
                <div class="col-6"><img src="~/img//m_bn_2_2.jpg" alt="" /></div>
                <div class="col-3 imggg"><img src="~/img//m_bn_2_3.jpg" alt="" /></div>
            </div>
        </div>
        <div class="title">
            <h2>SẢN PHẨM NỔI BẬT</h2>
        </div>
        @if (Model != null && Model.Any())
        {

            <div class="product">
                <div class="row">
                    @foreach (var product in lstNoiBat)
                    {
                        <div class="card-columns col-3" style="border: none">
                            <div class="card h-70 text-center" style="">
                                <a asp-controller="Home" asp-action="SanPhamChiTiet" asp-route-spct_id="@product.Id">
                                    <img src="~/img/@product.AnhDaiDien" class="card-img img-fluid" alt="" /></a>
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a asp-controller="Home" asp-action="SanPhamChiTiet" asp-route-spct_id="@product.Id">
                                            @Html.DisplayFor(modelItem => product.TenSPChiTiet)
                                            @*@(tensp = lstSP.FirstOrDefault(p => p.Id == product.IdSP).Ten)*@
                                        </a>
                                        <p class="card-text">  <span style="color: #c30005; font-weight: lighter;text-decoration: line-through;"></span>  @Html.DisplayFor(modelItem => product.GiaBan)VND</p>
                                    </h5>
                                    <p class="">
                                        <b>Trạng thái: @(product.TrangThai == 1 ? "Còn hàng" : "Hết hàng")</b>
                                    </p>
                                </div>

                            </div>
                            <br />
                        </div>

                    }
                </div>

            </div>
            <br />
            <div class="more">
                <a asp-controller="SanPham" asp-action="Index">XEM TẤT CẢ</a>
            </div>
        }
        else
        {
            <h3>Không có sản phẩm nào phù hợp</h3>
        }
        

        
       

    </div>
</div>