ProjectViews/Controllers/SanPhamChiTietController.cs
using _1_API.ViewModel.SanPham;
using _1_API.ViewModel.SanphamChitiet;
using Data.ModelsClass;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectViews.IServices;
using static _1_API.ViewModel.SanphamChitiet.SanPhamChiTietModel;

namespace ProjectViews.Controllers
{
    public class SanPhamChiTietController : Controller
    {
        private readonly ILogger<SanPhamChiTietController> _logger;
        private readonly IWebHostEnvironment _webHost;
        private readonly IAllServices _services;
        public SanPhamChiTietController(ILogger<SanPhamChiTietController> logger, IWebHostEnvironment webHost, IAllServices services)
        {
            _logger = logger;
            _webHost = webHost;
            _services = services;
        }
        [HttpGet]
        public async Task<IActionResult> Index(string id)
        {
            var lstSPCT = await _services.GetAll<SanphamChitiet>("https://localhost:7203/api/SanphamChitiets/Get-All");
            var lstSP = await _services.GetAll<SanPham>("https://localhost:7203/api/SanPhams/Get-All");
            var lstKichCo = await _services.GetAll<KichCo>("https://localhost:7203/api/KichCos/Get-All");
            var lstMauSac = await _services.GetAll<MauSac>("https://localhost:7203/api/MauSacs/Get-All");
            var spct = from a in lstSPCT.ToList().Where(p => p.IdSP == Guid.Parse(id))
                       join b in lstSP on a.IdSP equals b.Id
                       join d in lstMauSac on a.IdMauSac equals d.Id
                       select new ViewSanPhamChiTiet()
                       {
                           Id= a.Id,
                           GiaBan = a.GiaBan,
                           TenMauSac=d.TenMau,
                           TrangThai = a.TrangThai == 1 ? "Đang hoạt động" : "Ngưng hoạt động",
                           MaSPChiTiet = a.MaSPChiTiet,
                           TenSPChiTiet = a.TenSPChiTiet,
                           AnhDaiDien = a.AnhDaiDien
                       };
            ViewData["idSanPham"] = id;
            return View(spct);
        }
        [HttpGet]
        public async Task<IActionResult> Create(string id)
        {         
            var lstSP = await _services.GetAll<SanPham>("https://localhost:7203/api/SanPhams/Get-All");
            ViewData["lstSP"] = lstSP.ToList();
            var lstMauSac = await _services.GetAll<MauSac>("https://localhost:7203/api/MauSacs/Get-All");
            ViewData["lstMauSac"] = lstMauSac.ToList();
            var lstTheLoai = await _services.GetAll<TheLoai>("https://localhost:7203/api/TheLoais/Get-All");
            ViewData["lstTheLoai"] = lstTheLoai.ToList();
            var lstHang = await _services.GetAll<Hang>("https://localhost:7203/api/Hangs/Get-All");
            var sp = from a in lstSP.ToList()
                     join b in lstHang.ToList() on a.IdHang equals b.Id
                     select new ViewSanPham()
                     {
                         Id = a.Id,
                         Ten = a.Ten,
                         TrangThai = a.TrangThai == 1 ? "Đang hoạt động" : "Ngưng hoạt động",
                         TenHang = b.TenHang
                     };
            var sp1 = sp.FirstOrDefault(p => p.Id == Guid.Parse(id));
            ViewData["SanPham"] = sp1;
            SanPhamChiTietModel spmodel = new SanPhamChiTietModel();
            spmodel.IdSP = Guid.Parse(id);
            foreach(var item in lstTheLoai)
            {
                spmodel.TheLoai.Add(new SelectListItem { Text = item.TenTheLoai, Value = item.Id.ToString() });
            }
            return View(spmodel);
        }


        [HttpPost]
        public async Task<IActionResult> Create(SanPhamChiTietModel model)
        {
            var lstSP = await _services.GetAll<SanPham>("https://localhost:7203/api/SanPhams/Get-All");
            ViewData["lstSP"] = lstSP.ToList();
            var lstMauSac = await _services.GetAll<MauSac>("https://localhost:7203/api/MauSacs/Get-All");
            ViewData["lstMauSac"] = lstMauSac.ToList();
            var lstTheLoai = await _services.GetAll<TheLoai>("https://localhost:7203/api/TheLoais/Get-All");
            ViewData["lstTheLoai"] = lstTheLoai.ToList();
            var lstHang = await _services.GetAll<Hang>("https://localhost:7203/api/Hangs/Get-All");
            var sp = from a in lstSP.ToList()
                     join b in lstHang.ToList() on a.IdHang equals b.Id
                     select new ViewSanPham()
                     {
                         Id = a.Id,
                         Ten = a.Ten,
                         TrangThai = a.TrangThai == 1 ? "Đang hoạt động" : "Ngưng hoạt động",
                         TenHang = b.TenHang
                     };
            var sp1 = sp.FirstOrDefault(p => p.Id == (model.IdSP));
            ViewData["SanPham"] = sp1;
            SanPhamChiTietModel spmodel = new SanPhamChiTietModel();
            spmodel.IdSP = model.IdSP;
            foreach (var item in lstTheLoai)
            {
                spmodel.TheLoai.Add(new SelectListItem { Text = item.TenTheLoai, Value = item.Id.ToString() });
            }
            if (model.GiaNhap > model.GiaBan)
            {
                ModelState.AddModelError("","Giá bán phải cao hơn giá nhập");
            }
            if (model.Selected.Count == 0)
            {
                ModelState.AddModelError("", "Bạn chưa chọn thể loại cho sản phẩm");
            }
            if (ModelState.IsValid)
            {
                string uniqueFileName1 = null;
                string uniqueFileName2 = null;
                string uniqueFileName3= null;
                string uniqueFileName4= null;

                if (model.ImageFile != null && model.ImageFile1 != null && model.ImageFile2 != null && model.ImageFile3 != null)
                {
                    string uploadFolder = Path.Combine(_webHost.WebRootPath, "AnhChiTietSanPham");
                    uniqueFileName1 = Guid.NewGuid().ToString() + "_" + model.ImageFile.FileName;
                    string filepath = Path.Combine(uploadFolder, uniqueFileName1);
                    var filestream = new FileStream(filepath, FileMode.Create);
                    model.ImageFile.CopyTo(filestream);

                    string uploadFolder1 = Path.Combine("C:\\Users\\nguye\\Source\\Repos\\NET105_Project\\CustomerViews\\wwwroot\\", "img");
                    var anh1 = uniqueFileName1;
                    string filepath5 = Path.Combine(uploadFolder1, anh1);
                    var filestream5 = new FileStream(filepath5, FileMode.Create);
                    model.ImageFile.CopyTo(filestream5);

                    uniqueFileName2 = Guid.NewGuid().ToString() + "_" + model.ImageFile1.FileName;
                    string filepath1 = Path.Combine(uploadFolder, uniqueFileName2);
                    var filestream1 = new FileStream(filepath1, FileMode.Create);
                    model.ImageFile1.CopyTo(filestream1);

                    var anh2 = uniqueFileName2;
                    string filepath6 = Path.Combine(uploadFolder1, anh2);
                    var filestream6 = new FileStream(filepath6, FileMode.Create);
                    model.ImageFile1.CopyTo(filestream6);

                    uniqueFileName3 = Guid.NewGuid().ToString() + "_" + model.ImageFile2.FileName;
                    string filepath2 = Path.Combine(uploadFolder, uniqueFileName3);
                    var filestream2 = new FileStream(filepath2, FileMode.Create);
                    model.ImageFile2.CopyTo(filestream2);

                    var anh3 = uniqueFileName3;
                    string filepath7 = Path.Combine(uploadFolder1, anh3);
                    var filestream7 = new FileStream(filepath7, FileMode.Create);
                    model.ImageFile2.CopyTo(filestream7);

                    uniqueFileName4 = Guid.NewGuid().ToString() + "_" + model.ImageFile3.FileName;
                    string filepath3 = Path.Combine(uploadFolder, uniqueFileName4);
                    var filestream3 = new FileStream(filepath3, FileMode.Create);
                    model.ImageFile3.CopyTo(filestream3);

                    var anh4 = uniqueFileName4;
                    string filepath8 = Path.Combine(uploadFolder1, anh4);
                    var filestream8 = new FileStream(filepath8, FileMode.Create);
                    model.ImageFile3.CopyTo(filestream8);
                };
                CreateSanphamChitiet spct = new CreateSanphamChitiet()
                {
                    IdSP= model.IdSP,
                    TenChiTiet = model.TenSPChiTiet,
                    IdMauSac= model.IdMauSac,
                    GiaBan = model.GiaBan,
                    GiaNhap=model.GiaNhap,
                    TrangThai = model.TrangThai,
                    AnhDaiDien = uniqueFileName1,
                    Selected = model.Selected,
                    AnhPhu1 = uniqueFileName2,
                    AnhPhu2 = uniqueFileName3,
                    AnhPhu3 = uniqueFileName4,
                };
                
                await _services.Add("https://localhost:7203/api/SanphamChiTiets/", spct);
                var a = model.IdSP.ToString();
                return RedirectToAction("Index", "SanphamChitiet", new {id = model.IdSP});
            }
            return View(spmodel);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            await _services.Remove<SanphamChitiet>("https://localhost:7203/api/SanphamChiTiets/GetById/", "https://localhost:7203/api/SanphamChiTiets/Delete/", id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var lstSP = await _services.GetAll<SanPham>("https://localhost:7203/api/SanPhams/Get-All");
            ViewData["lstSP"] = lstSP.ToList();

ProjectViews/Controllers/SizeSanPhamController.cs
using _1_API.ViewModel.SanPham;
using _1_API.ViewModel.SizeSanPham;
using Data.ModelsClass;
using Microsoft.AspNetCore.Mvc;
using ProjectViews.IServices;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace ProjectViews.Controllers
{
    public class SizeSanPhamController : Controller
    {
        private readonly ILogger<SizeSanPhamController> _logger;
        private readonly IAllServices _services;
        public SizeSanPhamController(ILogger<SizeSanPhamController> logger, IAllServices services)
        {
            _logger = logger;
            _services = services;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Create(string id)
        {
            var lstSize = await _services.GetAll<KichCo>("https://localhost:7203/api/KichCos/Get-All");
            ViewData["lstSize"] = lstSize.ToList();
            var lstSizeSP = await _services.GetAll<SizeSanPham>("https://localhost:7203/api/SizeSanPhams/Get-All");
            lstSizeSP = lstSizeSP.Where(p => p.IdSanPhamChiTiet == Guid.Parse(id));
            var obj = from a in lstSizeSP
                      join b in lstSize on a.IdSize equals b.Id
                      select new SizeSanPhamModel()
                      {
                          Id = a.Id,
                          Size = b.Size.ToString(),
                          SoLuong = a.SoLuong
                      };
            var objs = obj.ToList();
            ViewData["lstSizeSP"] = objs;
            CreateSizeSanPham cr = new CreateSizeSanPham();
            cr.IdSanPhamChiTiet = Guid.Parse(id);
            return View(cr);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSizeSanPham model)
        {
            var lstSize = await _services.GetAll<KichCo>("https://localhost:7203/api/KichCos/Get-All");
            ViewData["lstSize"] = lstSize.ToList();
            var lstSizeSP = await _services.GetAll<SizeSanPham>("https://localhost:7203/api/SizeSanPhams/Get-All");
            lstSizeSP = lstSizeSP.Where(p => p.IdSanPhamChiTiet == model.IdSanPhamChiTiet);
            var obj = from a in lstSizeSP
                      join b in lstSize on a.IdSize equals b.Id
                      select new SizeSanPhamModel()
                      {
                          Id = a.Id,
                          Size = b.Size.ToString(),
                          SoLuong = a.SoLuong
                      };
            ViewData["lstSizeSP"] = obj.ToList();
            if (ModelState.IsValid)
            {
                var lstSanPham = await _services.GetAll<SizeSanPham>("https://localhost:7203/api/SizeSanPhams/Get-All");
                var ten = lstSanPham.FirstOrDefault(p => p.IdSanPhamChiTiet == model.IdSanPhamChiTiet && p.IdSize == model.IdSize);
                if (ten != null)
                {
                    ModelState.AddModelError("", "Size đã có trong bảng");
                    return View(model);
                }
                else
                {
                    CreateSizeSanPham sp = new CreateSizeSanPham()
                    {
                        IdSanPhamChiTiet = model.IdSanPhamChiTiet,
                        IdSize = model.IdSize,
                        SoLuong = model.SoLuong
                    };
                    await _services.Add("https://localhost:7203/api/SizeSanPhams/", sp);
                    return RedirectToAction("Create", new { id = model.IdSanPhamChiTiet.ToString() });
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {

            var spid = await _services.GetById<SizeSanPham>("https://localhost:7203/api/SizeSanPhams/GetById/", Guid.Parse(id));
            var lstSize = await _services.GetAll<KichCo>("https://localhost:7203/api/KichCos/Get-All");
            ViewData["lstSize"] = lstSize.ToList();
            UpdateSizeSanPham nvmd = new UpdateSizeSanPham()
            {
                Id = Guid.Parse(id),
                IdSanPhamChiTiet = spid.IdSanPhamChiTiet,
                IdSize = spid.IdSize,
                SoLuong = spid.SoLuong
            };
            return View(nvmd);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UpdateSizeSanPham model)
        {

            await _services.Update<UpdateSizeSanPham>("https://localhost:7203/api/SizeSanPhams/Update/", model, model.Id);
            return RedirectToAction("Create",new {id = model.IdSanPhamChiTiet});
        }

    }
}

ProjectViews/Views/SanPhamChiTiet/Create.cshtml
@model _1_API.ViewModel.SanphamChitiet.SanPhamChiTietModel
@using Data.ModelsClass
@using _1_API.ViewModel.SanPham
@using _1_API.ViewModel.SanphamChitiet
@{
    ViewData["Title"] = "Create";
    var lstSp = ViewData["lstSP"] as List<SanPham>;
    var lstMS = ViewData["lstMauSac"] as List<MauSac>;
    var sanpham = ViewData["SanPham"] as ViewSanPham;
    var lstTheloai = ViewData["lstTheLoai"] as List<TheLoai>;
}

<h1>Thêm Chi Tiết Sản Phẩm</h1>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdSP" />
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="control-label">Tên sản phẩm</label>
                        <input class="form-control" value="[@sanpham.TenHang]@sanpham.Ten" disabled/>
                    </div>
                    <div class="form-group">
                        <label asp-for="TenSPChiTiet" class="control-label">Tên chi tiết</label>
                        <input asp-for="TenSPChiTiet" class="form-control" />
                        <span asp-validation-for="TenSPChiTiet" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Màu sắc</label>
                        <select asp-for="IdMauSac" class="form-select">
                            @foreach (var item in lstMS)
                            {
                                <option value="@item.Id">
                                    @item.TenMau
                                </option>
                            }
                        </select>
                    </div>
                    
                </div>
                <div class="col-md-5">
                    <div class="form-group">
                        <label asp-for="GiaNhap" class="control-label">Giá Nhập</label>
                        <input asp-for="GiaNhap" type="number" class="form-control" />
                        <span asp-validation-for="GiaNhap" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="GiaBan" class="control-label">Giá Bán</label>
                        <input asp-for="GiaBan" type="number" class="form-control" />
                        <span asp-validation-for="GiaBan" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TrangThai" class="control-label">Trạng thái</label>
                        <select asp-for="TrangThai" class="form-select">
                            <option value="1" selected>Đang hoạt động</option>
                            <option value="0">Ngưng hoạt động</option>
                        </select>
                        <span asp-validation-for="TrangThai" class="text-danger"></span>
                    </div>

                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="TheLoai" class="control-label">Thể loại</label>
                        @foreach (var item in Model.TheLoai)
                        {
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"
                                       name="Selected"
                                       value="@item.Value"
                                       @if(Model.Selected.Contains(item.Value))
                                       {
                                <text> checked </text>
                                }
                                /> @item.Text
                                </label>
                            </div>
                        }
                        <span asp-validation-for="Selected" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <div class="row">
                        <label asp-for="ImageFile" class="control-label">Ảnh đại diện</label>
                    </div>

                    <img id="FrontImagePrv" src="" alt="Logo Image" width="150px" height="150px" style="border:1px; margin-top: 0px; margin-left:0px" />
                    <div class="custom-file mt-2">
                        <input asp-for="ImageFile" class="custom-file-input" id="FLFrontImage" accept="image/*"
                               onchange="document.getElementById('FrontImagePrv').src = window.URL.createObjectURL(this.files[0])" />
                    </div>
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <label asp-for="ImageFile1" class="control-label">Ảnh phụ 1</label>
                    </div>

                    <img id="FrontImagePrv1" src="" alt="Logo Image" width="150px" height="150px" style="border:1px; margin-top: 0px; margin-left:0px" />
                    <div class="custom-file mt-2">
                        <input asp-for="ImageFile1" class="custom-file-input" id="FLFrontImage" accept="image/*"
                               onchange="document.getElementById('FrontImagePrv1').src = window.URL.createObjectURL(this.files[0])" />
                    </div>
                    <span asp-validation-for="ImageFile1" class="text-danger"></span>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <label asp-for="ImageFile2" class="control-label">Ảnh phụ 2</label>
                    </div>

                    <img id="FrontImagePrv2" src="" alt="Logo Image" width="150px" height="150px" style="border:1px; margin-top: 0px; margin-left:0px" />
                    <div class="custom-file mt-2">
                        <input asp-for="ImageFile2" class="custom-file-input" id="FLFrontImage" accept="image/*"
                               onchange="document.getElementById('FrontImagePrv2').src = window.URL.createObjectURL(this.files[0])" />
                    </div>
                    <span asp-validation-for="ImageFile2" class="text-danger"></span>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <label asp-for="ImageFile3" class="control-label">Ảnh phụ 3</label>
                    </div>

                    <img id="FrontImagePrv3" src="" alt="Logo Image" width="150px" height="150px" style="border:1px; margin-top: 0px; margin-left:0px" />
                    <div class="custom-file mt-2">
                        <input asp-for="ImageFile3" class="custom-file-input" id="FLFrontImage" accept="image/*"
                               onchange="document.getElementById('FrontImagePrv3').src = window.URL.createObjectURL(this.files[0])" />
                    </div>
                    <span asp-validation-for="ImageFile3" class="text-danger"></span>
                </div>
            </div>



            <div class="row mt-3">

                <div class="col-md-12">
                    <div class="form-group" style="text-align: center">
                        <input type="submit" value="Thêm" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        $(".custom-file-input").on("change", function () {
            var filename = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(filename);
        });
    </script>
    

}

ProjectViews/Views/SanPhamChiTiet/Details.cshtml
@model _1_API.ViewModel.SanphamChitiet.SanPhamChiTietDetails

@{
    ViewData["Title"] = "Details";
}

<h1>Chi Tiết Sản Phẩm Chi Tiết </h1>
<div>
    <hr />
    <div class="row">
        <div class="col-md-3">
            <div class="row">
                <label class="control-label">Ảnh đại diện</label>
            </div>
            <img src="@("~/AnhChiTietSanPham/"+Model.AnhDaiDien)" alt="@Model.AnhDaiDien" asp-append-version="true" width="120px" height="140px" />
        </div>
        <div class="col-md-3">
            <div class="row">
                <label class="control-label">Ảnh phụ 1</label>
            </div>
            <img src="@("~/AnhChiTietSanPham/"+Model.AnhPhu1)" alt="@Model.AnhPhu1" asp-append-version="true" width="120px" height="140px" />
        </div>
        <div class="col-md-3">
            <div class="row">
                <label class="control-label">Ảnh phụ 2</label>
            </div>
            <img src="@("~/AnhChiTietSanPham/"+Model.AnhPhu2)" alt="@Model.AnhPhu2" asp-append-version="true" width="120px" height="140px" />
        </div>
        <div class="col-md-3">
            <div class="row">
                <label class="control-label">Ảnh phụ 3</label>
            </div>
            <img src="@("~/AnhChiTietSanPham/"+Model.AnhPhu3)" alt="@Model.AnhPhu3" asp-append-version="true" width="120px" height="140px" />
        </div>
    </div>
    <dl class="row mt-3">
        
        <div class="col-md-6">
            <dt class="col-sm-2">
                Tên Sản Phẩm
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TenSP)
            </dd>
            <dt class="col-sm-2">
                Tên Chi Tiết
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TenChiTiet)
            </dd>
            <dt class="col-sm-2">
                Màu Sắc
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MauSac)
            </dd>
            <dt class="col-sm-2">
                Thể Loại
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TheLoai)
            </dd>
        </div>
        <div class="col-md-6">
            <dt class="col-sm-2">
                Giá Nhập
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.GiaNhap)
            </dd>
            <dt class="col-sm-2">
                Giá Bán
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.GiaBan)
            </dd>
            <dt class="col-sm-2">
                Trạng Thái
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TrangThai)
            </dd>
        </div>
        
        
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ProjectViews/Views/SanPhamChiTiet/Index.cshtml
@model IEnumerable<_1_API.ViewModel.SanphamChitiet.ViewSanPhamChiTiet>

@{
    ViewData["Title"] = "Index";
    string idSanPham = ViewData["idSanPham"] as string;
}

<h1>Chi Tiết Sản Phẩm</h1>

<p>
    <a asp-controller="SanPhamChiTiet" asp-action="Create" asp-route-id="@idSanPham">Thêm chi tiết sản phẩm</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Ảnh
            </th>   
            <th>
                Mã
            </th>
            <th>
                Tên chi tiết
            </th>
            <th>
                Màu sắc
            </th>
            <th>
                Giá bán
            </th>
            <th>
                Trạng thái
            </th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    <img src="@("~/AnhChiTietSanPham/"+item.AnhDaiDien)" alt="@item.AnhDaiDien" asp-append-version="true" width="120px" height="140px" />
            </td>           
            <td>
                @Html.DisplayFor(modelItem => item.MaSPChiTiet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenSPChiTiet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenMauSac)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaBan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrangThai)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Cập nhật</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Chi Tiết</a> |
                    <a asp-controller="SizeSanPham" asp-action="Create" asp-route-id="@item.Id">Quản lý size</a>
            </td>
        </tr>
}
    </tbody>
</table>